### ISSUE TITLE
Error Cannot read property 'year' of undefined at JobNewComponent.setJob (job-new.component.ts:120)

### ISSUE THREAD

**Issue by VKirstein** [WaCoDiS/job-manager-ui#1]
Der Button listener "Job checken und ausführen" wartet immer auf eine Kalenderauswahl es gibt keine Defaultwerte für sofort ausführen und mehrfache Ausführung sodass es nur möglich ist einen Job anzulegen mit einem einmalig definierten Ausführungszeitpunkt über den Kalender.

**Comment by imkeines** [comment]
Dieser Fehler sollte mit dem Push 'adjust planning functionality: enable immediate and interval processing' angepasst sein.
