### ISSUE TITLE
Prozessspezifische Parameterwerte

### ISSUE THREAD

**Issue by SebaDro** [WaCoDiS/job-manager-ui#10]
Bei allen Produkten steht als Eingabeparameterbeschreibung "Optische Satellitenszene". Das macht die Auswahl ob Sentinel 1 oder Sentinel 2 betrachtet werden soll eigentlich obsolet oder nicht?

_Originally posted by @VKirstein in https://github.com/WaCoDiS/job-manager-ui/issues/7#issuecomment-684895549_

**Comment by SebaDro** [comment]
Mit dem 1.2.0 Release werden für alle Produkte, dort wo es sinnvoll ist, bestimmte Werte für Inputparameter vorgeschlagen. Z.B wird für den Prozess "Änderung der Flächenvitalität" die Werte "Sentinel-2" und "Level 2A" für die _CopernicusSubsets_ vorgeschlagen. 
@VKirstein: Schau doch einmal, ob das dem entspricht, was du dir vorgestellt hast.

**Comment by VKirstein** [comment]
Ja das passt so. Finde ich gut. Das erleichtert die Erstellung. Wollte unter anderem darauf hinweisen das Sentinel 2 ja nur optische Bilder liefert. Sentinel 1 wären ja keine optischen Bilder sondern Radarbilder daher beschreibt die Bezeichnung des Feldes schon die Auswahl.

**Comment by SebaDro** [comment]
Ok, super. Dann kann ich den Issue erst einmal schließen.
