### ISSUE TITLE
Input specific time intervals

### ISSUE THREAD

**Issue by SebaDro** [WaCoDiS/job-manager-ui#12]
Recently, the WaCoDiS Job Definition API changed the strategy for defining the temporal coverage for input datasets. First, the temporal coverage object has changed as follows:
```json
"temporalCoverage": {
    "duration": "string",
    "offset": "string"
  }
```
`duration`: backwards duration in ISO8601 format 
`offset`: an offset  in ISO8601 format that defines the starting time for the backwards duration 
With `offset` and `duration` one can define arbitrary temporal coverages in the past and is not limited on `offsets` beginning from the processing time. However, `offset` is optional. If not set or `null`, the `duration` will start from the processing time.

In addition, the API differentiates between two strategies: definition of a common time interval that is applicable for all inputs and input specific time intervals.  Following some examples for both strategies.
1. Common time interval:
```
{
...
  "processingTool": "de.hsbo.wacodis.land_cover_classification",
  "temporalCoverage": {
    "duration": "P7D"
  },
  "inputs": [
    {
      "sourceType": "CopernicusSubsetDefinition",
      "identifier": "OPTICAL_IMAGES_SOURCES",
      "satellite": "sentinel-2",
      "maximumCloudCoverage": 15
    },
    {
      "sourceType": "StaticSubsetDefinition",
      "identifier": "REFERENCE_DATA",
      ...
    }
  ],
  ...
}
```
2. Input specific time interval
```
{
  ...
  "processingTool": "de.hsbo.wacodis.forest_vitality_change",
  "temporalCoverage": {
    "duration": "P7D"
  },
  "inputs": [
    {
      "sourceType": "CopernicusSubsetDefinition",
      "identifier": "OPTICAL_IMAGES_SOURCES_1",
      "satellite": "sentinel-2",
      "maximumCloudCoverage": 15,
      "temporalCoverage": {
        "duration": "P2M"
      }
    },
    {
      "sourceType": "CopernicusSubsetDefinition",
      "identifier": "OPTICAL_IMAGES_SOURCES_2",
      "satellite": "sentinel-2",
      "maximumCloudCoverage": 15,
      "temporalCoverage": {
        "duration": "P2M",
        "offset": "P2M"
      }
    },
  ],
  ...
}
```

**Comment by imkeines** [comment]
This is fully implemented with commit e32df44a734c7a468770c5cb4e402a839f09af55 (develp branch)
