### ISSUE TITLE
Job Modal nach absenden des Jobs schließen

### ISSUE THREAD

**Issue by VKirstein** [WaCoDiS/job-manager-ui#2]
Nachdem man den Job kontrolliert hat und den Job abschickt bleibt das Modal noch offen. Besser wäre wenn es sich wieder schließen würde, dann hat der Nutzer eine erste Rückmeldung dass der Job angelegt wurde.

**Comment by imkeines** [comment]
Im push mit dem Titel 'adjust planning functionality: enable immediate and interval processing' ist dies angepasst worden. Das Modal schließt sich nun nachdem der Abschicken Knopf gedrückt wurde.
