### ISSUE TITLE
Hinweis für Differenz GMT Zeit (Prozesszeit) und Nutzer Zeitzone

### ISSUE THREAD

**Issue by VKirstein** [WaCoDiS/job-manager-ui#3]
Die Zeit die über den Kalender eingegeben wird für die Job-Ausführung ist die aktuelle Browserzeit beim Nutzer (Nutzer Zeitzone), die aber nicht die Systemzeit des ausführenden Elements ist (GMT) vielleicht irgendwo den Hinweis geben.

**Comment by imkeines** [comment]
Die Zeitangabe (Zone) wird nun genauer dargestellt, sowohl beim Job anlegen, als auch in der Übersicht.

**Comment by imkeines** [comment]
Die Zeiten sind nun in der deutschen Schreibweise verfügbar. Die Zeiten scheinen in der UI richtig angezeigt und im System richtig transformiert zu werden. Daher würde ich diesen Issue nun schließen.
