### ISSUE TITLE
Weiterer Übergabeparameter der "Retries" eines Jobs

### ISSUE THREAD

**Issue by VKirstein** [WaCoDiS/job-manager-ui#5]
Retries Parameter möglicherweise noch als Übergabeparameter in der UI oder einen default Wert von mind. 2 festlegen.

**Comment by imkeines** [comment]
Hallo, ich habe noch zwei weitere optionale Eingabefelder hinzugefügt, sodass der/die User/in die Möglichkeit hat Angaben zu machen zur 1. Anzahl der möglichen Versuche, falls ein Versuch fehlschlägt und 2. zum Zeitabstand zwischen diesen Versuchen. Werden hierzu keine Angaben gegeben habe ich jetzt erstmal Defaulwerte angeben : Anzahl Versuche: 3, Zeitabstand: 500ms.
