### ISSUE TITLE
StaticSubsetDefinition Layer bei Landbedeckungsklassifikation mit Hinweis auf Trainingsdaten

### ISSUE THREAD

**Issue by VKirstein** [WaCoDiS/job-manager-ui#7]
Es ist bis jetzt nur als Kommentar, dass ein WFS Layer übergebn werden soll. Gut wäre wenn man erkennen könnte, dass es sich bei dem WFS Layer um die Trainigsdaten/Referenzdaten handeln soll

**Comment by imkeines** [comment]
Hey Verena, super, danke für den Bericht! Ich habe heute in der App noch einmal etwas umstrukturiert sodass die Informationen, die die Eingabeinformationen betreffen aus einem Konfigurationsfile eingelesen werden. Sebastian und ich würden dann diesen File noch einmal anpassen und würden dich auch nochmal um passende, aussagekräftige Begriffe bitten, die gut verständlich sind.  Außerdem eventuell noch einen kurzen Hint, den man als kurze Erklärung unter dem EIngabefeld anzeigen kann (in Fällen, wo dies eventuell noch hilfreich ist). Wir würden uns dann nochmal zurück melden!

**Comment by VKirstein** [comment]
Hi @imkeines  alles klar weiß ich Bescheid. Dann meldet euch einfach wenn ihr Input braucht ;)

**Comment by imkeines** [comment]
Sehr gut, machen wir! :-)

**Comment by SebaDro** [comment]
Das neueste Deployment enthält nun aussagekräftige Labesls für Inputs sowie zusätzliche Beschreibungen, wo es notwendig war. Bitte einmal testen, ob das so in Ordnung ist. Falls ja würde ich den Issue dann schließen.

**Comment by VKirstein** [comment]
Vielen Dank für die Bearbeitung. Drei Punkte sind mir noch aufgefallen:

- es wäre hilfreich wenn neben der namentlichen Auswahl des Jobs zusätzlich entsprechend eine kurze Beschreibung des Produkts dargestellt werden würde, was Eingangsparameter sind / was man als Ergebnis erwarten kann / Aufgabe des Produkts.

- Die Produkt Benennung "Änderung der Waldvitalität" würden wir gerne allgemeiner fassen als "Änderung der Vitalität" wenn das geht, da unter anderem auch aufgekommen ist die Vitalität auf den Grünlandflächen verschiedener Zeitpunkte zu monitoren, was ja mittels der Maskenübergabe mit dem Produkt möglich wäre. Bei der Maske müsste dann auch die Beschreibung verallgemeinert werden.

- bei allen Produkten steht als Eingabeparameterbeschreibung "Optische Satellitenszene". Das macht die Auswahl ob Sentinel 1 oder Sentinel 2 betrachtet werden soll eigentlich obsolet oder nicht?

**Comment by imkeines** [comment]
Hey Verena, danke für das Feedback! 
Das sollte eigentlich recht schnell zu bearbeiten gehen. Wir schauen uns das die nächsten Tage genauer an und melden uns zurück!

**Comment by SebaDro** [comment]
>es wäre hilfreich wenn neben der namentlichen Auswahl des Jobs zusätzlich entsprechend eine kurze Beschreibung des Produkts dargestellt werden würde, was Eingangsparameter sind / was man als Ergebnis erwarten kann / Aufgabe des Produkts.

Das könnte als zusätzlicher ProcessMappings-Parameter mit aufgenommen werden, bedarf dann aber kleiner Anpassung der UI.

>Die Produkt Benennung "Änderung der Waldvitalität" würden wir gerne allgemeiner fassen als "Änderung der Vitalität" wenn das geht, da unter anderem auch aufgekommen ist die Vitalität auf den Grünlandflächen verschiedener Zeitpunkte zu monitoren, was ja mittels der Maskenübergabe mit dem Produkt möglich wäre. Bei der Maske müsste dann auch die Beschreibung verallgemeinert werden.

Hier müsste lediglich der hinterlegte Wert in den ProcessMappings angepasst werden. Eine Anpassung der UI ist nicht notwendig.

>bei allen Produkten steht als Eingabeparameterbeschreibung "Optische Satellitenszene". Das macht die Auswahl ob Sentinel 1 oder Sentinel 2 betrachtet werden soll eigentlich obsolet oder nicht?

Diesen Punkt hatten wir bereits intern diskutiert. Hierzu müssten die ProcessMappings überarbeitet und die UI entsprechend angepasst werden. I.d.T. macht es fachlich keinen Sinn, wenn für bestimmte Produkte sowohl Sentinel-1 als auch Sentinel-2 Datensätze ausgewählt werden können.

**Comment by SebaDro** [comment]
>es wäre hilfreich wenn neben der namentlichen Auswahl des Jobs zusätzlich entsprechend eine kurze Beschreibung des Produkts dargestellt werden würde, was Eingangsparameter sind / was man als Ergebnis erwarten kann / Aufgabe des Produkts.

Wurde nach  #9 übertragen

>Die Produkt Benennung "Änderung der Waldvitalität" würden wir gerne allgemeiner fassen als "Änderung der Vitalität" wenn das geht, da unter anderem auch aufgekommen ist die Vitalität auf den Grünlandflächen verschiedener Zeitpunkte zu monitoren, was ja mittels der Maskenübergabe mit dem Produkt möglich wäre. Bei der Maske müsste dann auch die Beschreibung verallgemeinert werden.

Die Konfiguration wurde entsprechend abgeändert, sodass in der UI dieser Prozess nun anders beannnt ist. 

>bei allen Produkten steht als Eingabeparameterbeschreibung "Optische Satellitenszene". Das macht die Auswahl ob Sentinel 1 oder Sentinel 2 betrachtet werden soll eigentlich obsolet oder nicht?

Wurde nach  #10 übertragen

Damit kann der ursprüngliche Issue geschlossen werden.
