### ISSUE TITLE
Jobs Übersicht zeigt limitierte Anzahl an Jobs?

### ISSUE THREAD

**Issue by VKirstein** [WaCoDiS/job-manager-ui#8]
Mir ist aufgefallen als ich ein paar Test Jobs beim aufräumen in der JobÜbersicht gelöscht habe, dass nachdem ich einen Job aus der Liste gelöscht habe, einer zuvor nicht in der liste stehender Job sichtbar wird. Daher die Vermutung, dass auf der Übersichtsseite nur eine bestimmte Menge an Jobs angezeigt wird und der Rest ausgeblendet bleibt.

**Comment by SebaDro** [comment]
Wurde umgesetzt mit ae1002f.
