### ISSUE TITLE
Produktbeschreibung bereitstellen

### ISSUE THREAD

**Issue by SebaDro** [WaCoDiS/job-manager-ui#9]
Es wäre hilfreich wenn neben der namentlichen Auswahl des Jobs zusätzlich entsprechend eine kurze Beschreibung des Produkts dargestellt werden würde, was Eingangsparameter sind / was man als Ergebnis erwarten kann / Aufgabe des Produkts.

_Originally posted by @VKirstein in https://github.com/WaCoDiS/job-manager-ui/issues/7#issuecomment-684895549_

**Comment by imkeines** [comment]
This is implemented with commit 0a325961ee6ded61aa8cf7cbcffb4ca9de903ef0 (branch develop)
